version: '3.3'

services:
  db:
    image: postgres:16-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: taskmaster
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: