"""add_size_to_files

Revision ID: db2f4d61338d
Revises: 9487bc0f5b40
Create Date: 2025-07-27 23:06:29.191997

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db2f4d61338d"
down_revision: Union[str, Sequence[str], None] = "9487bc0f5b40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "size")
    # ### end Alembic commands ###
